Dev to Master
Ankr-network/mirage-widget-unity pull request #1
Opened 2023-03-24 08:34 UTC by Antivortex

2023-03-24 09:31 UTC, Vukiz requested changes

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Android-WebView-Plugin/app/.gitignore
> +/build
I don't think we need a second gitignore, right?

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Android-WebView-Plugin/app/src/main/java/com/mirage/miragewebviewandroidplugin/MirageWebViewActivity.java
> +        _exitButton.setOnClickListener(v -> finish());
extract finish into separate method.

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Android-WebView-Plugin/app/src/main/java/com/mirage/miragewebviewandroidplugin/MirageWebViewActivity.java
> +
remove extra line

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Android-WebView-Plugin/app/src/main/java/com/mirage/miragewebviewandroidplugin/UnityBridge.java
> +        this.context = context;
name it _context and you will no have to use this.

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Android-WebView-Plugin/app/src/test/java/com/mirage/miragewebviewandroidplugin/ExampleUnitTest.java
> +    @Test
remove examples

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Widget/Packages/packages-lock.json
> +    "com.unity.modules.unitywebrequestassetbundle": {
I think we should be able to remove a bunch of useless default packages from it, right?

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Widget/UserSettings/Search.settings
> +{}
usersettings should be ignored

2023-03-24 09:31 UTC, Vukiz commented on Mirage-Widget/ankr-sdk-renaming.py
> +def is_desired_extension(filename):
this is not needed, right?

2023-04-07 06:58 UTC, Vukiz approved these changes, later dismissed

2023-04-11 10:07 UTC, Antivortex commented
Now this PR contains all previously reviewed PRs with all of the changes requested in this PR

2023-04-11 10:08 UTC, Vukiz approved these changes

2023-04-11 10:09 UTC, merged